name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ASPNETCORE_URLS: 'http://localhost:5000'
  DIR_WEBAPP: './SiteContagem'
  LOG_EXECUTION_WEB: 'execution-webapp.log'
  TEST_SCRIPTS: './Tests/tests-sitecontagem.js'
  
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.100
    - name: Executar a aplicação a ser testada em background (nohup)
      run: |
        dotnet publish ${{ env.DIR_WEBAPP }} -c Release -o app
        cd ./app
        nohup dotnet SiteContagem.dll > ${{ env.LOG_EXECUTION_WEB }} 2>&1 &
        echo 'Aguardando a inicialização da aplicação a ser testada...'
        sleep 10s
    - name: Testes de carga com k6
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ${{ env.TEST_SCRIPTS }}
    - name: Testes
      if: always()
      run: |
        curl http://localhost:5000
    - name: Executar log execução da aplicação após testes
      if: always()
      run: |
        cd ./app
        cat ${{ env.LOG_EXECUTION_WEB }}

  build:
    needs: [tests]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testes
      run: echo Testes funcionaram...
