name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DIR_WEBAPP: ./SiteContagem
  TEST_SCRIPTS: ./Tests/tests-sitecontagem.js
  
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testes de carga com k6
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ${{ env.TEST_SCRIPTS }}

  build:
    needs: [tests]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testes
      run: echo Testes funcionaram...
